name: Deploy
on:
  push:
    branches: [ "main", "frontend"]
  workflow_dispatch:
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - name: Checkout frontend
        uses: actions/checkout@v3
        with:
          ref: frontend
          path: frontend
      - name: Build frontend
        uses: actions/setup-node@v1
      - run: cd frontend
      - run: npm install
      - run: npm run build
        env:
          CI: true
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           BRANCH: pages
           FOLDER: src/out
